
id = "Eszenn.apManual"
name = "Webfishing Archipelago Manual"
description = "Reworks a number of features to work better for the Archipelago Manual"
version = "1.0.0"
homepage = "https://github.com/Eszenn/Webfishing-AP-Manual/"
author = "Eszenn"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./ArchipelagoTweaks/ArchipelagoTweaks.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
